# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:              Philo 



author:
  name:             Christian Giliberto
  github:           cgiliberto

# Google-analytics
google-analytics:
  id:               ""

# URL
#url:                "https://AWEEKJ.github.io" # the base hostname & protocol for your site
url:                "https://philo.wtf" # use this url when develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           America/New_York
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "https://philo.wtf/about/"
  - name:           "Professional Services"
    url:            "https://philo.wtf/services/"
  - name:           "Archive"
    url:            "https://philo.wtf/archive/"
  - name:           "Tags"
    url:            "https://philo.wtf/tags/"
  - name:	    "Notebooks"
    url:            "https://philo.wtf/notebooks/"
  - name:           "Github"
    url:            "https://github.com/cgiliberto"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
